version: '3.7'

services:
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        env_file: ./env/.mysql
        environment:
            DATABASE_HOST: mysql
        ports:
            - 80:80
        depends_on:
            - mysql
        volumes:
            - ./public:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/php.ini
    mysql:
        image: mysql:5.7.28
        env_file: ./env/.mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.8
        env_file: ./env/.phpmyadmin
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
        ports:
            - 55555:80
        volumes:
            - ./phpmyadmin/data:/sessions
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - 1080:1080
            - 1025:1025
    composer:
        image: composer:1.9.0
        command: 'composer require firebase/php-jwt'
        volumes:
          - ./public:/app
        depends_on:
            - php
